name: uri_escape
description: Escape text for uri
version: 1.0.0
homepage: https://trhhosting.com
author: TRH <software@trhhosting.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
